controller_manager:
  ros__parameters:
    update_rate: 200  # Hz, can adjust for sim performance

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    hsrb4s/arm_flex_joint_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: arm_flex_joint
      pid:
        p: 8.0
        i: 1000.0
        d: 0.0
        i_clamp: 500.0

    hsrb4s/arm_lift_joint_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: arm_lift_joint
      pid:
        p: 8.0
        i: 1000.0
        d: 0.0
        i_clamp: 500.0

    hsrb4s/arm_roll_joint_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: arm_roll_joint
      pid:
        p: 8.0
        i: 1000.0
        d: 0.0
        i_clamp: 500.0

    hsrb4s/head_pan_joint_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: head_pan_joint
      pid:
        p: 8.0
        i: 1000.0
        d: 0.0
        i_clamp: 500.0

    hsrb4s/head_tilt_joint_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: head_tilt_joint
      pid:
        p: 8.0
        i: 1000.0
        d: 0.0
        i_clamp: 500.0

    hsrb4s/wrist_flex_joint_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: wrist_flex_joint
      pid:
        p: 8.0
        i: 1000.0
        d: 0.0
        i_clamp: 500.0

    hsrb4s/wrist_roll_joint_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: wrist_roll_joint
      pid:
        p: 8.0
        i: 1000.0
        d: 0.0
        i_clamp: 500.0

    hsrb4s/hand_motor_joint_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: hand_motor_joint
      pid:
        p: 8.0
        i: 1000.0
        d: 0.0
        i_clamp: 500.0
